management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:ams_database
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:7075/realms/external
        provider:
          keycloak:
            issuer-uri: http://localhost:7075/realms/external
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-name: external-client
            client-id: external-client
            client-secret: ubTg2FYB7AH724Cnzn2vq64BdGIAXuOX
            scope: openid
            authorization-grant-type: authorization_code

kafka:
  bootstrap-servers: localhost:9092
  topic: VISIT_EVENT_TOPIC_TEST
  group-id: AMS_GROUP_1
  enabled: true
  max-replay-count: 2

ams:
  security:
    enabled: true
  async-config:
    enabled: true

jwt:
  auth:
    converter:
      resource-id: external-client
      principal-attribute: preferred_username

url:
  visitor-management-service: http://localhost:9002

logging:
  level:
    sql: debug
    root: info